spring:
  application:
    name: inventory-service
  jpa:
    defer-datasource-initialization: true
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true