INSERT INTO books (id, isbn, genre, title, author) VALUES (1, '1-86092-049-7', 'Modern Times', 'The Grass is Always Greener', 'Jeffrey Archer');
INSERT INTO books (id, isbn, genre, title, author) VALUES (2, '1-86092-012-8', 'Crime', 'Murder!', 'Arnold Bennett');
INSERT INTO books (id, isbn, genre, title, author) VALUES (3, '1-86092-022-5', 'First Edition', 'A Boy at Seven', 'John Bidwell');
INSERT INTO books (id, isbn, genre, title, author) VALUES (4, '1-86092-010-1', 'Romance', 'The Higgler', 'A. E. Coppard');
INSERT INTO books (id, isbn, genre, title, author) VALUES (5, '1-86092-025-x', 'Classic', 'The Open Boat', 'Stephen Crane');
INSERT INTO books (id, isbn, genre, title, author) VALUES (6, '1-86092-034-9', 'Classic', 'The Great Switcheroo', 'Roald Dahl');
INSERT INTO books (id, isbn, genre, title, author) VALUES (7, '1-86092-003-9', 'Crime', 'The Speckled Band', 'Sir Arthur Conan Doyle');
INSERT INTO books (id, isbn, genre, title, author) VALUES (8, '1-86092-038-1', 'Suspense', 'The Signalman', 'Charles Dickens');
INSERT INTO books (id, isbn, genre, title, author) VALUES (9, '1-86092-031-4', 'Crime', 'The Five Orange Pips', 'Sir Arthur Conan Doyle');
INSERT INTO books (id, isbn, genre, title, author) VALUES (10, '1-86092-021-7', 'Classic', 'A Chance for Mr Lever', 'Graham Greene');
